name: shell commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: string
        run echo"Welcome to first workflow"
      - name: multipline script
        run: |
          node -v
          npm -v   