name: Outputs-demo
on:
   workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs: 
       outputj1s1: ${{ steps.j1s1.outputs.job1step1 }}
       outputj1s2: ${{ steps.j1s2.outputs.job1step2 }}
    steps:
      - id: j1s1
        run: echo "::set-output name=job1step1::output from j1s1" 
      - id: j12
        run: echo "::set-output name=job1step2::output from j1s2" 
        
