name: Outputs-demo
on:
   workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs: 
       output1: ${{ steps.step1.outputs.job1step1 }}
       output2: ${{ steps.step2.outputs.job1step2 }}
    steps:
      - id: step1
        run: echo "::set-output name=job1step1::output from j1s1" 
        
      - id: step2
        #run: echo "::set-output name=job1step2::output from j1s2" 
        run: echo "{job1step2}={output from j1s2}" >> $GITHUB_OUTPUT
        
